/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Juan Milanese (https://sketchfab.com/juanmilanese)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/f6c153fe21ad490c916bb94c04290d0a
title: Japanese Lamp / Chōchin
*/

import React, { useRef, useEffect} from 'react'
import { useGLTF } from '@react-three/drei'

export default function Lamp(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('Models/Lamp/scene.gltf');

  useEffect(()=>{
    console.log(group);
  })

  return (
    <group ref={group} {...props} dispose={null} scale={[0.01,0.01,0.01]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, 0]}>
              <mesh material={materials['Scene_-_Root']} geometry={nodes.Big_Chochin_M__0.geometry} />
            </group>
          </group>
        </group>
      </group>
      <pointLight {...props} position={[-4,7,-4]} intensity={0.1} color={"#ffffff"}/>
    </group>
    
  )
}

useGLTF.preload('Models/Lamp/scene.gltf')
