/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ZoeChuiYan (https://sketchfab.com/zoelofutureworks)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/organics-small-tree-81f88945fc274c0da9fea9d777e8beb6
title: Organics: Small Tree
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three";

export default function Sakura(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('Models/Sakura/scene.gltf');

  useEffect(()=>{
    group.current.traverse( function( node ) { if ( node instanceof THREE.Mesh ) { node.castShadow = true; node.receiveShadow=true; } } );
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.lambert2SG} geometry={nodes.mesh_0.geometry} />
        <mesh material={materials.lambert3SG} geometry={nodes.mesh_1.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('Models/Sakura/scene.gltf')
